version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: ember-cli-babel
    versions:
    - 7.23.1
    - 7.24.0
    - 7.25.0
    - 7.26.0
    - 7.26.1
  - dependency-name: ember-source
    versions:
    - 3.24.1
    - 3.25.0
    - 3.25.1
    - 3.25.2
    - 3.25.3
  - dependency-name: ember-cli
    versions:
    - 3.24.0
    - 3.25.0
    - 3.25.1
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
  - dependency-name: ember-template-lint
    versions:
    - 2.18.0
    - 2.18.1
    - 2.19.0
    - 2.20.0
  - dependency-name: ember-auto-import
    versions:
    - 1.10.1
  - dependency-name: "@types/ember"
    versions:
    - 3.16.3
  - dependency-name: acorn
    versions:
    - 6.4.2
